# Generated by Django 4.0.5 on 2024-08-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccountcreation',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentaccountcreation',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
