# Generated by Django 4.0.5 on 2024-08-22 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfileSetUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_student_id', models.CharField(max_length=8, unique=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('interests', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='portfolio/')),
                ('social_media', models.URLField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, max_length=150, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificate/')),
                ('education', models.CharField(blank=True, max_length=150, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, to_field='student_id')),
            ],
        ),
    ]
